DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'krug_app') THEN
    CREATE ROLE krug_app LOGIN PASSWORD 'ПРИДУМАЙТЕ_НАДЁЖНЫЙ_ПАРОЛЬ';
  END IF;
END $$;
GRANT USAGE ON SCHEMA krug TO krug_app;
GRANT USAGE ON SCHEMA extensions TO krug_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA krug TO krug_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA krug TO krug_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA krug TO krug_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA krug GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO krug_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA krug GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO krug_app;
ALTER ROLE krug_app SET search_path = krug, extensions, public;
REVOKE ALL ON SCHEMA krug FROM PUBLIC;
REVOKE ALL ON SCHEMA krug FROM anon, authenticated;
